// Mock data derived from design-spec prototype content

import type { Trade, Account, Setup, LearningResource, Rule, WeeklyReview } from "@/types"

export const mockAccounts: Account[] = [
  {
    id: "acc-1",
    name: "FXify 100K — Phase 2",
    broker: "FXify",
    type: "PROP_FIRM",
    initialBalance: 100000,
    currency: "USD",
    timezone: "America/New_York",
    propFirmRules: {
      maxDrawdownPct: 10,
      dailyLossPct: 5,
      maxTradesPerDay: 3,
      targetPct: 8,
      allowedSymbols: ["NQ", "ES", "MNQ"],
    },
    createdAt: "2026-01-01T00:00:00Z",
  },
]

export const mockSetups: Setup[] = [
  {
    id: "setup-1",
    name: "Opening Range Break",
    abbreviation: "OR",
    market: "NQ Futures",
    direction: "AMBAS",
    status: "ACTIVO",
    description: "Ruptura del rango de apertura de los primeros 15 minutos en killzone NY.",
    aplusChecklist: ["Confluencia HTF", "Killzone activa", "Volumen sobre promedio", "Stop estructural"],
    standardChecklist: ["Setup #1 o #2 del día", "Risk ≤ 1R", "RR ≥ 1.5"],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "setup-2",
    name: "Failed Auction",
    abbreviation: "FA",
    market: "NQ Futures",
    direction: "AMBAS",
    status: "ACTIVO",
    description: "Subasta fallida en nivel de liquidez previo.",
    aplusChecklist: ["Confluencia HTF", "Killzone activa", "Volumen sobre promedio", "Stop estructural"],
    standardChecklist: ["Setup #1 o #2 del día", "Risk ≤ 1R", "RR ≥ 1.5"],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "setup-3",
    name: "MMXM — Breaker Block",
    abbreviation: "BB",
    market: "NQ Futures",
    direction: "AMBAS",
    status: "ACTIVO",
    description: "Modelo MMXM en breaker block con confluencia de sesión.",
    aplusChecklist: ["Confluencia HTF", "Killzone activa", "Volumen sobre promedio", "Stop estructural"],
    standardChecklist: ["Setup #1 o #2 del día", "Risk ≤ 1R", "RR ≥ 1.5"],
    createdAt: "2026-01-01T00:00:00Z",
  },
]

export const mockTrades: Trade[] = [
  {
    id: "trade-1",
    direction: "LONG",
    symbol: "NQ",
    accountId: "acc-1",
    setupId: "setup-1",
    entry: 21450,
    stop: 21380,
    target: 21590,
    size: 2,
    date: "2026-05-14",
    openTime: "09:32",
    session: "New York",
    tags: ["A+"],
    notes: "Entrada en zona de liquidez después de sweep. Confluencia perfecta con HTF.",
    rMultiple: 2.0,
    pnl: 2800,
    createdAt: "2026-05-14T09:32:00Z",
  },
  {
    id: "trade-2",
    direction: "SHORT",
    symbol: "ES",
    accountId: "acc-1",
    setupId: "setup-2",
    entry: 5280,
    stop: 5295,
    target: 5250,
    size: 1,
    date: "2026-05-13",
    openTime: "10:15",
    session: "New York",
    tags: ["Plan"],
    rMultiple: 2.0,
    pnl: 1500,
    createdAt: "2026-05-13T10:15:00Z",
  },
  {
    id: "trade-3",
    direction: "LONG",
    symbol: "NQ",
    accountId: "acc-1",
    setupId: "setup-3",
    entry: 21200,
    stop: 21160,
    target: 21280,
    size: 1,
    date: "2026-05-12",
    openTime: "14:20",
    session: "New York",
    tags: ["Off-plan", "Impulsivo"],
    notes: "Tomé el trade fuera de killzone. Error de disciplina.",
    rMultiple: -1,
    pnl: -800,
    createdAt: "2026-05-12T14:20:00Z",
  },
]

export const mockResources: LearningResource[] = [
  {
    id: "res-1",
    title: "Volume Profile · Aitor",
    type: "LIBRO",
    author: "Aitor Lobato",
    source: "Aitor Lobato",
    date: "2026-05-16",
    notes: "Cap 4–6: cómo identificar value area shift. Aplicar al ORB de mañana.",
    tags: ["futures", "profile"],
    markedForReview: true,
    progressPct: 60,
    createdAt: "2026-05-16T00:00:00Z",
  },
  {
    id: "res-2",
    title: "Liquidity Grab masterclass",
    type: "VIDEO",
    author: "MotiveWave",
    source: "MotiveWave",
    date: "2026-05-14",
    notes: "Backtest 100 grabs en ES — wr 71% con confluencia HTF.",
    tags: ["liquidity", "ICT"],
    markedForReview: true,
    progressPct: 67,
    createdAt: "2026-05-14T00:00:00Z",
  },
  {
    id: "res-3",
    title: "Trading in the Zone — cap 8",
    type: "LIBRO",
    author: "Mark Douglas",
    source: "Mark Douglas",
    date: "2026-05-12",
    notes: "Probabilistic mindset. Estoy pensando en outcomes vs. proceso.",
    tags: ["psicologia"],
    markedForReview: false,
    progressPct: 80,
    createdAt: "2026-05-12T00:00:00Z",
  },
  {
    id: "res-4",
    title: "Tilt management protocol",
    type: "NOTA",
    author: "Propio",
    source: "Propio",
    date: "2026-05-10",
    notes: "Después de -2R, walk away 30min. Apliqué viernes y funcionó.",
    tags: ["psicologia", "disciplina"],
    markedForReview: true,
    createdAt: "2026-05-10T00:00:00Z",
  },
  {
    id: "res-5",
    title: "Backtest London Reversal Q2",
    type: "BACKTEST",
    author: "Propio",
    source: "Propio",
    date: "2026-05-08",
    notes: "100 trades · WR 58% · Avg R 1.4. Mejor en martes/miércoles.",
    tags: ["FX", "reversal"],
    markedForReview: false,
    createdAt: "2026-05-08T00:00:00Z",
  },
  {
    id: "res-6",
    title: "Order Flow podcast — ep. 142",
    type: "PODCAST",
    author: "Spotgamma",
    source: "Spotgamma",
    date: "2026-05-05",
    notes: "Spotgamma sobre delta divergencia en NQ. Aplicar a 0DTE.",
    tags: ["order-flow"],
    markedForReview: false,
    progressPct: 80,
    createdAt: "2026-05-05T00:00:00Z",
  },
  {
    id: "res-7",
    title: "VWAP-reclaim drill — semana 1",
    type: "DRILL",
    author: "Propio",
    source: "Propio",
    date: "2026-05-03",
    notes: "Replay 50 reclaims · identifiqué 3 falsos en cada uno.",
    tags: ["VWAP", "drill"],
    markedForReview: false,
    progressPct: 50,
    createdAt: "2026-05-03T00:00:00Z",
  },
  {
    id: "res-8",
    title: "Risk-of-ruin calculator",
    type: "HERRAMIENTA",
    author: "Externa",
    source: "Externa",
    date: "2026-05-01",
    notes: "Configurado con 1% risk · ruin prob < 0.1% con 200 trades.",
    tags: ["risk"],
    markedForReview: false,
    createdAt: "2026-05-01T00:00:00Z",
  },
]

export const mockRules: Rule[] = [
  { id: "rule-sys-1", name: "Operar fuera de sesión", description: "Trade abierto fuera de las killzones permitidas.", severity: "CRÍTICA", isSystem: true, enabled: true, violationsThisMonth: 2 },
  { id: "rule-sys-2", name: "Exceder máximo de trades", description: "Más trades en un día del límite de la cuenta.", severity: "CRÍTICA", isSystem: true, enabled: true, violationsThisMonth: 3 },
  { id: "rule-sys-3", name: "Pérdida diaria sobre límite", description: "La pérdida del día superó el límite diario configurado.", severity: "CRÍTICA", isSystem: true, enabled: true, violationsThisMonth: 1 },
  { id: "rule-sys-4", name: "Operar símbolo no permitido", description: "Se operó un instrumento fuera de la lista permitida.", severity: "CRÍTICA", isSystem: true, enabled: true, violationsThisMonth: 1 },
]

export const mockReviews: WeeklyReview[] = [
  {
    id: "review-1",
    accountId: "acc-1",
    weekLabel: "Sem. 20",
    weekRange: "14–20 may 2026",
    tradeCount: 23,
    netPnl: 2640,
    winRate: 65,
    disciplineScore: 78,
    executiveSummary: "Semana sólida con buena ejecución en killzones NY. Algunos errores de disciplina en sesión London.",
    whatWorked: "Entradas en OR con confluencia HTF. Gestión de riesgo consistente.",
    toImprove: "Reducir trades en sesión Asia. Esperar confirmación antes de entrar.",
    status: "draft",
    createdAt: "2026-05-20T00:00:00Z",
  },
]
