// Mock data derived from design-spec prototype content

import type { Trade, Account, Setup, LearningResource, Rule, WeeklyReview, Market, RulesSeverity } from "@/types"

export const mockAccounts: Account[] = [
  {
    id: "acc-1",
    name: "FXify 100K — Phase 2",
    broker: "FXify",
    type: "PROP_FIRM",
    initialBalance: 100000,
    currency: "USD",
    timezone: "America/New_York",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "acc-2",
    name: "FTMO Swing 50K",
    broker: "FTMO",
    type: "PROP_FIRM",
    initialBalance: 50000,
    currency: "USD",
    timezone: "America/New_York",
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "acc-3",
    name: "Personal IB",
    broker: "Interactive Brokers",
    type: "PERSONAL",
    initialBalance: 25000,
    currency: "USD",
    timezone: "America/New_York",
    createdAt: "2026-03-01T00:00:00Z",
  },
]

export const mockSetups: Setup[] = [
  {
    id: "setup-1",
    name: "Opening Range Break",
    abbreviation: "OR",
    market: "NQ Futures",
    direction: "AMBAS",
    status: "ACTIVO",
    description: "Ruptura del rango de apertura de los primeros 15 minutos en killzone NY.",
    aplusChecklist: [
      "Range definido en primeros 15min",
      "Breakout con volumen > 150% promedio",
      "Confluencia HTF 1H/4H alcista",
      "Stop bajo mínimo del rango",
      "Killzone NY activa (9:30–11:00)",
    ],
    standardChecklist: [
      "Setup #1 o #2 del día",
      "Risk ≤ 1R",
      "RR mínimo 1.5:1",
      "Sin noticias en próximos 30min",
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "setup-2",
    name: "Failed Auction",
    abbreviation: "FA",
    market: "NQ Futures",
    direction: "AMBAS",
    status: "ACTIVO",
    description: "Subasta fallida en nivel de liquidez previo.",
    aplusChecklist: [
      "Subasta previa claramente identificada",
      "Rechazo en nivel con volumen alto",
      "Confluencia HTF 4H/D confirma dirección",
      "Stop estructural sobre high/low previo",
      "Sesión London o NY activa",
    ],
    standardChecklist: [
      "Setup #1 o #2 del día",
      "Risk ≤ 1R",
      "RR mínimo 2:1",
      "Nivel de liquidez claramente visible",
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "setup-3",
    name: "MMXM — Breaker Block",
    abbreviation: "BB",
    market: "NQ Futures",
    direction: "AMBAS",
    status: "ACTIVO",
    description: "Modelo MMXM en breaker block con confluencia de sesión.",
    aplusChecklist: [
      "Breaker block identificado en HTF (1H+)",
      "Mitigation en zona de OB previo",
      "Estructura interna rota (CHoCH confirmado)",
      "Entrada en zona premium/discount",
      "Killzone London o NY activa",
    ],
    standardChecklist: [
      "Modelo MMXM completo presente",
      "Risk ≤ 1R",
      "RR mínimo 2:1",
      "Sin solapamiento de noticias mayores",
    ],
    createdAt: "2026-01-01T00:00:00Z",
  },
]

export const mockTrades: Trade[] = [
  {
    id: "trade-1",
    direction: "LONG",
    symbol: "NQ",
    accountId: "acc-1",
    setupId: "setup-1",
    entry: 21450,
    stop: 21380,
    target: 21590,
    size: 2,
    date: "2026-05-14",
    openTime: "09:32",
    session: "New York",
    tags: ["A+"],
    notes: "Entrada en zona de liquidez después de sweep. Confluencia perfecta con HTF.",
    rMultiple: 2.0,
    pnl: 2800,
    createdAt: "2026-05-14T09:32:00Z",
  },
  {
    id: "trade-2",
    direction: "SHORT",
    symbol: "ES",
    accountId: "acc-1",
    setupId: "setup-2",
    entry: 5280,
    stop: 5295,
    target: 5250,
    size: 1,
    date: "2026-05-13",
    openTime: "10:15",
    session: "New York",
    tags: ["Plan"],
    rMultiple: 2.0,
    pnl: 1500,
    createdAt: "2026-05-13T10:15:00Z",
  },
  {
    id: "trade-3",
    direction: "LONG",
    symbol: "NQ",
    accountId: "acc-1",
    setupId: "setup-3",
    entry: 21200,
    stop: 21160,
    target: 21280,
    size: 1,
    date: "2026-05-12",
    openTime: "14:20",
    session: "New York",
    tags: ["Off-plan", "Impulsivo"],
    notes: "Tomé el trade fuera de killzone. Error de disciplina.",
    rMultiple: -1,
    pnl: -800,
    createdAt: "2026-05-12T14:20:00Z",
  },
  {
    id: "trade-4",
    direction: "SHORT",
    symbol: "GC",
    accountId: "acc-2",
    setupId: "setup-2",
    entry: 2345.5,
    stop: 2352.0,
    target: 2332.0,
    size: 1,
    date: "2026-05-15",
    openTime: "08:45",
    session: "London",
    tags: ["A+"],
    notes: "Failed auction en resistencia semanal. Volumen de rechazo muy claro.",
    rMultiple: 2.1,
    pnl: 1350,
    createdAt: "2026-05-15T08:45:00Z",
  },
  {
    id: "trade-5",
    direction: "LONG",
    symbol: "NQ",
    accountId: "acc-2",
    setupId: "setup-3",
    entry: 21680,
    stop: 21620,
    target: 21800,
    size: 2,
    date: "2026-05-16",
    openTime: "03:10",
    session: "Asia",
    tags: ["Plan"],
    notes: "Breaker block en zona de 4H. Entrada limpia pero sesión Asia con poco volumen.",
    rMultiple: -1,
    pnl: -960,
    createdAt: "2026-05-16T03:10:00Z",
  },
  {
    id: "trade-6",
    direction: "LONG",
    symbol: "ES",
    accountId: "acc-3",
    setupId: "setup-1",
    entry: 5310,
    stop: 5298,
    target: 5346,
    size: 2,
    date: "2026-05-19",
    openTime: "09:35",
    session: "New York",
    tags: ["A+"],
    notes: "OR perfecto. Rango de 15min muy neto, breakout con gap y volumen >180%.",
    rMultiple: 3.0,
    pnl: 4320,
    createdAt: "2026-05-19T09:35:00Z",
  },
  {
    id: "trade-7",
    direction: "SHORT",
    symbol: "NQ",
    accountId: "acc-1",
    setupId: "setup-3",
    entry: 21520,
    stop: 21555,
    target: 21450,
    size: 1,
    date: "2026-05-20",
    openTime: "15:30",
    session: "London Close",
    tags: ["Plan"],
    notes: "Breaker block en London Close. RR justo pero confluencia sólida.",
    rMultiple: 2.0,
    pnl: 1400,
    createdAt: "2026-05-20T15:30:00Z",
  },
  {
    id: "trade-8",
    direction: "SHORT",
    symbol: "GC",
    accountId: "acc-3",
    setupId: "setup-1",
    entry: 2360.0,
    stop: 2367.5,
    target: 2345.0,
    size: 1,
    date: "2026-05-21",
    openTime: "09:40",
    session: "New York",
    tags: ["Off-plan"],
    notes: "Quise forzar un OR en GC sin confirmar rango. Stop muy ajustado.",
    rMultiple: -1,
    pnl: -600,
    createdAt: "2026-05-21T09:40:00Z",
  },
]

export const mockResources: LearningResource[] = [
  {
    id: "res-1",
    title: "Volume Profile · Aitor",
    type: "LIBRO",
    author: "Aitor Lobato",
    source: "Aitor Lobato",
    date: "2026-05-16",
    notes: "Cap 4–6: cómo identificar value area shift. Aplicar al ORB de mañana.",
    tags: ["futures", "profile"],
    markedForReview: true,
    progressPct: 60,
    createdAt: "2026-05-16T00:00:00Z",
    updatedAt: "2026-05-16T00:00:00Z",
    status: "IN_PROGRESS",
    isFavorite: false,
  },
  {
    id: "res-2",
    title: "Liquidity Grab masterclass",
    type: "VIDEO",
    author: "MotiveWave",
    source: "MotiveWave",
    date: "2026-05-14",
    notes: "Backtest 100 grabs en ES — wr 71% con confluencia HTF.",
    tags: ["liquidity", "ICT"],
    markedForReview: true,
    progressPct: 67,
    createdAt: "2026-05-14T00:00:00Z",
    updatedAt: "2026-05-14T00:00:00Z",
    status: "IN_PROGRESS",
    isFavorite: false,
  },
  {
    id: "res-3",
    title: "Trading in the Zone — cap 8",
    type: "LIBRO",
    author: "Mark Douglas",
    source: "Mark Douglas",
    date: "2026-05-12",
    notes: "Probabilistic mindset. Estoy pensando en outcomes vs. proceso.",
    tags: ["psicologia"],
    markedForReview: false,
    progressPct: 80,
    createdAt: "2026-05-12T00:00:00Z",
    updatedAt: "2026-05-12T00:00:00Z",
    status: "IN_PROGRESS",
    isFavorite: true,
  },
  {
    id: "res-4",
    title: "Tilt management protocol",
    type: "NOTA",
    author: "Propio",
    source: "Propio",
    date: "2026-05-10",
    notes: "Después de -2R, walk away 30min. Apliqué viernes y funcionó.",
    tags: ["psicologia", "disciplina"],
    markedForReview: true,
    createdAt: "2026-05-10T00:00:00Z",
    updatedAt: "2026-05-10T00:00:00Z",
    status: "COMPLETED",
    isFavorite: false,
  },
  {
    id: "res-5",
    title: "Backtest London Reversal Q2",
    type: "BACKTEST",
    author: "Propio",
    source: "Propio",
    date: "2026-05-08",
    notes: "100 trades · WR 58% · Avg R 1.4. Mejor en martes/miércoles.",
    tags: ["FX", "reversal"],
    markedForReview: false,
    createdAt: "2026-05-08T00:00:00Z",
    updatedAt: "2026-05-08T00:00:00Z",
    status: "COMPLETED",
    isFavorite: false,
  },
  {
    id: "res-6",
    title: "Order Flow podcast — ep. 142",
    type: "PODCAST",
    author: "Spotgamma",
    source: "Spotgamma",
    date: "2026-05-05",
    notes: "Spotgamma sobre delta divergencia en NQ. Aplicar a 0DTE.",
    tags: ["order-flow"],
    markedForReview: false,
    progressPct: 80,
    createdAt: "2026-05-05T00:00:00Z",
    updatedAt: "2026-05-05T00:00:00Z",
    status: "IN_PROGRESS",
    isFavorite: false,
  },
  {
    id: "res-7",
    title: "VWAP-reclaim drill — semana 1",
    type: "DRILL",
    author: "Propio",
    source: "Propio",
    date: "2026-05-03",
    notes: "Replay 50 reclaims · identifiqué 3 falsos en cada uno.",
    tags: ["VWAP", "drill"],
    markedForReview: false,
    progressPct: 50,
    createdAt: "2026-05-03T00:00:00Z",
    updatedAt: "2026-05-03T00:00:00Z",
    status: "IN_PROGRESS",
    isFavorite: false,
  },
  {
    id: "res-8",
    title: "Risk-of-ruin calculator",
    type: "HERRAMIENTA",
    author: "Externa",
    source: "Externa",
    date: "2026-05-01",
    notes: "Configurado con 1% risk · ruin prob < 0.1% con 200 trades.",
    tags: ["risk"],
    markedForReview: false,
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-01T00:00:00Z",
    status: "PENDING",
    isFavorite: false,
  },
]

export const mockRules: Rule[] = [
  { id: "rule-sys-1", name: "Operar fuera de sesión", description: "Trade abierto fuera de las killzones permitidas.", severity: "CRÍTICA", isSystem: true, enabled: true, violationsThisMonth: 2 },
  { id: "rule-sys-2", name: "Exceder máximo de trades", description: "Más trades en un día del límite de la cuenta.", severity: "CRÍTICA", isSystem: true, enabled: true, violationsThisMonth: 3 },
  { id: "rule-sys-3", name: "Pérdida diaria sobre límite", description: "La pérdida del día superó el límite diario configurado.", severity: "CRÍTICA", isSystem: true, enabled: true, violationsThisMonth: 1 },
  { id: "rule-sys-4", name: "Operar símbolo no permitido", description: "Se operó un instrumento fuera de la lista permitida.", severity: "CRÍTICA", isSystem: true, enabled: true, violationsThisMonth: 1 },
  { id: "rule-cus-1", name: "Promediar en pérdida", description: "Agregar posición a un trade en pérdida para bajar el precio promedio.", severity: "CRÍTICA" as RulesSeverity, isSystem: false, enabled: true, violationsThisMonth: 1 },
  { id: "rule-cus-2", name: "Operar en noticias", description: "Abrir trade 15 min antes o durante publicación de noticia de alto impacto.", severity: "CRÍTICA" as RulesSeverity, isSystem: false, enabled: true, violationsThisMonth: 2 },
  { id: "rule-cus-3", name: "Sin checklist completado", description: "Abrir trade sin haber marcado todos los ítems del checklist del setup.", severity: "MENOR" as RulesSeverity, isSystem: false, enabled: true, violationsThisMonth: 0 },
  { id: "rule-cus-4", name: "Trade de venganza", description: "Abrir trade inmediatamente tras pérdida sin pausa mínima de 15 minutos.", severity: "MENOR" as RulesSeverity, isSystem: false, enabled: false, violationsThisMonth: 3 },
]

export const mockMarkets: Market[] = [
  // FUTUROS
  { symbol: "NQ", name: "Nasdaq-100 E-mini", category: "FUTUROS", exchange: "CME", tickSize: "0.25", pointValue: "$20", currency: "USD", sessions: ["NY AM", "NY PM"], description: "Índice tecnológico de mayor volatilidad. Principal instrumento de trading.", isWatchlisted: true },
  { symbol: "ES", name: "S&P 500 E-mini", category: "FUTUROS", exchange: "CME", tickSize: "0.25", pointValue: "$50", currency: "USD", sessions: ["NY AM", "NY PM"], description: "Índice más líquido del mundo. Spreads mínimos, alta correlación con macro.", isWatchlisted: true },
  { symbol: "MNQ", name: "Micro Nasdaq-100", category: "FUTUROS", exchange: "CME", tickSize: "0.25", pointValue: "$2", currency: "USD", sessions: ["NY AM", "NY PM"], description: "Versión micro del NQ. Ideal para sizing reducido o cuentas prop firma.", isWatchlisted: true },
  { symbol: "MES", name: "Micro S&P 500", category: "FUTUROS", exchange: "CME", tickSize: "0.25", pointValue: "$5", currency: "USD", sessions: ["NY AM", "NY PM"], description: "Versión micro del ES.", isWatchlisted: false },
  { symbol: "GC", name: "Gold", category: "FUTUROS", exchange: "COMEX", tickSize: "0.10", pointValue: "$100", currency: "USD", sessions: ["London", "NY AM"], description: "Oro al contado (futuros). Alta reacción a eventos macro y noticias Fed.", isWatchlisted: true },
  { symbol: "CL", name: "Crude Oil WTI", category: "FUTUROS", exchange: "NYMEX", tickSize: "0.01", pointValue: "$1,000", currency: "USD", sessions: ["London", "NY AM"], description: "Petróleo crudo. Muy sensible a inventarios semanales EIA.", isWatchlisted: false },
  { symbol: "RTY", name: "Russell 2000 E-mini", category: "FUTUROS", exchange: "CME", tickSize: "0.10", pointValue: "$50", currency: "USD", sessions: ["NY AM", "NY PM"], description: "Small caps. Más volátil que ES, menor liquidez.", isWatchlisted: false },
  // FX
  { symbol: "EURUSD", name: "Euro / US Dollar", category: "FX", exchange: "OTC", tickSize: "0.00001", pointValue: "$10 / lot", currency: "USD", sessions: ["London", "NY AM"], description: "Par más líquido del mundo. Killzone London 02:00–05:00 ET.", isWatchlisted: true },
  { symbol: "GBP USD", name: "Pound / US Dollar", category: "FX", exchange: "OTC", tickSize: "0.00001", pointValue: "$10 / lot", currency: "USD", sessions: ["London", "NY AM"], description: "Cable. Alta volatilidad en noticias UK y Fed.", isWatchlisted: true },
  { symbol: "USDJPY", name: "US Dollar / Yen", category: "FX", exchange: "OTC", tickSize: "0.001", pointValue: "$9.1 / lot", currency: "USD", sessions: ["Asia", "London"], description: "Par de carry trade. Muy activo en sesión Asia.", isWatchlisted: false },
  { symbol: "XAUUSD", name: "Gold Spot FX", category: "FX", exchange: "OTC", tickSize: "0.01", pointValue: "$100 / lot", currency: "USD", sessions: ["London", "NY AM"], description: "Oro spot en mercado FX. Correlacionado con DXY.", isWatchlisted: false },
  // CRIPTO
  { symbol: "BTCUSD", name: "Bitcoin / US Dollar", category: "CRIPTO", exchange: "Binance / CME", tickSize: "1.00", pointValue: "1 BTC", currency: "USD", sessions: ["24h"], description: "Activo digital de mayor capitalización. Alta volatilidad, spreads variables.", isWatchlisted: true },
  { symbol: "ETHUSD", name: "Ethereum / US Dollar", category: "CRIPTO", exchange: "Binance / CME", tickSize: "0.01", pointValue: "1 ETH", currency: "USD", sessions: ["24h"], description: "Segunda criptomoneda por capitalización. Correlación alta con BTC.", isWatchlisted: false },
  { symbol: "SOLUSD", name: "Solana / US Dollar", category: "CRIPTO", exchange: "Binance", tickSize: "0.01", pointValue: "1 SOL", currency: "USD", sessions: ["24h"], description: "L1 de alta velocidad. Más volátil que ETH.", isWatchlisted: false },
  // EQUITIES
  { symbol: "AAPL", name: "Apple Inc.", category: "EQUITIES", exchange: "NASDAQ", tickSize: "0.01", pointValue: "$1 / acción", currency: "USD", sessions: ["NY AM", "NY PM"], description: "Mayor capitalización del mercado. Muy seguido en earnings.", isWatchlisted: false },
  { symbol: "NVDA", name: "NVIDIA Corp.", category: "EQUITIES", exchange: "NASDAQ", tickSize: "0.01", pointValue: "$1 / acción", currency: "USD", sessions: ["NY AM", "NY PM"], description: "Líder en GPUs y AI. Alta volatilidad, mueve el NQ.", isWatchlisted: true },
  { symbol: "TSLA", name: "Tesla Inc.", category: "EQUITIES", exchange: "NASDAQ", tickSize: "0.01", pointValue: "$1 / acción", currency: "USD", sessions: ["NY AM", "NY PM"], description: "Alta volatilidad individual. Reacciona fuerte a noticias del CEO.", isWatchlisted: false },
  { symbol: "SPY", name: "SPDR S&P 500 ETF", category: "EQUITIES", exchange: "NYSE", tickSize: "0.01", pointValue: "$1 / acción", currency: "USD", sessions: ["NY AM", "NY PM"], description: "ETF del S&P 500. Alternativa a ES para accounts sin futuros.", isWatchlisted: false },
]

export const mockReviews: WeeklyReview[] = [
  {
    id: "review-1",
    accountId: "acc-1",
    weekLabel: "Sem. 20",
    weekRange: "14–20 may 2026",
    tradeCount: 23,
    netPnl: 2640,
    winRate: 65,
    disciplineScore: 78,
    executiveSummary: "Semana sólida con buena ejecución en killzones NY. Algunos errores de disciplina en sesión London.",
    whatWorked: "Entradas en OR con confluencia HTF. Gestión de riesgo consistente.",
    toImprove: "Reducir trades en sesión Asia. Esperar confirmación antes de entrar.",
    status: "draft",
    createdAt: "2026-05-20T00:00:00Z",
  },
]
